# Generated by Django 4.2.7 on 2025-08-05 12:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Recipe title', max_length=200)),
                ('description', models.TextField(help_text='Brief description of the recipe')),
                ('category', models.CharField(choices=[('appetizer', 'Appetizer'), ('main_course', 'Main Course'), ('dessert', 'Dessert'), ('beverage', 'Beverage'), ('snack', 'Snack'), ('soup', 'Soup'), ('salad', 'Salad')], default='main_course', max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('prep_time', models.PositiveIntegerField(help_text='Preparation time in minutes')),
                ('cook_time', models.PositiveIntegerField(help_text='Cooking time in minutes')),
                ('servings', models.PositiveIntegerField(help_text='Number of servings', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('ingredients', models.TextField(help_text='List of ingredients (one per line)')),
                ('notes', models.TextField(blank=True, help_text='Additional notes or tips', null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='recipes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recipe',
                'verbose_name_plural': 'Recipes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField(help_text='Order of this step (1, 2, 3, etc.)')),
                ('title', models.CharField(help_text='Brief title for this step', max_length=100)),
                ('instruction', models.TextField(help_text='Detailed instruction for this step')),
                ('duration', models.PositiveIntegerField(blank=True, help_text='Time needed for this step in minutes (optional)', null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='steps/')),
                ('temperature', models.CharField(blank=True, help_text="Temperature setting (e.g., '350°F', 'Medium heat')", max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipe', models.ForeignKey(help_text='The recipe this step belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='core.recipe')),
            ],
            options={
                'verbose_name': 'Recipe Step',
                'verbose_name_plural': 'Recipe Steps',
                'ordering': ['step_number'],
                'unique_together': {('recipe', 'step_number')},
            },
        ),
    ]
