# Generated by Django 4.2.7 on 2025-08-12 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.CharField(blank=True, choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('dessert', 'Dessert'), ('snack', 'Snack')], max_length=20),
        ),
        migrations.AddField(
            model_name='recipe',
            name='dietary_preferences',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
